version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: news_postgres
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    build: .
    container_name: news_dashboard
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: newsdb
      DB_USER: postgres
      DB_PASSWORD: root

volumes:
  postgres_data: